version: "3.8"

services:
  aggregator:
    image: registry.digitalocean.com/csgo/aggregator:latest
    stop_signal: SIGINT
    environment:
      REDIS_URL: "redis://redis/"
    env_file: secrets.env
    ports:
      - "7000:7000"
    volumes:
      - './keystore.yaml:/usr/src/casino/keystore.yaml'

  redis:
    image: redis:6
  
  nginx:
    image: registry.digitalocean.com/csgo/frontend:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt:ro'
      - '../viz/nginx.conf:/etc/nginx/nginx.conf:ro'
    depends_on:
      - aggregator
